name: "God's Gallery"
favicon: null
layout_spectrum: 0.7992329471744597
typography_spectrum: 0.23693277197889984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.6522501045837998
  rhythmicContrast: 0.75
purpose: []
